### ISSUE TITLE
Cannot import "main" module

### ISSUE THREAD

**Issue by a904012** [lucascaton/code2pdf#4]
[Code2pdf v.1.0.0 // Python v.3.5.1 //Windows ] [Installed using git clone]

I am trying to execute the following code:
`from Code2pdf.code2pdf import Code2pdf`
`ifile,ofile,size = "test.py", "test.pdf", "A4"`
`pdf = Code2pdf(ifile, ofile, size)  # create the Code2pdf object`
`pdf.init_print()    # call print method to print pdf`

And I get the following error:
`ImportError: cannot import name 'main'`

**Comment by lucascaton** [comment]
Python? 🤔
