### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by StephanMeijer** [lucascaton/code2pdf#5]
Requests
1. New line for each file.
2. Python syntax highlighting

**Comment by lucascaton** [comment]
Hi @StephanMeijer, I'm very busy at the moment but PRs are welcome! 😄

**Comment by coderhs** [comment]
I am thinking of having a go at this issue, since I require it for work. But it seems prawn can't do css. We will have to change the PDF library to something like PDFKit. The change looks minimal.

I am also planning to use rouge syntax highlight library. Let me know what you think @lucascaton

**Comment by lucascaton** [comment]
Hey @coderhs, sounds good to me! 😄

**Comment by lucascaton** [comment]
https://rubygems.org/gems/code2pdf/versions/0.4.1

**Comment by coderhs** [comment]
👏  :clinking_glasses: 

Next I want to see If I can port this to `crystal` or run it in `mruby` this project is a great candidate to be distributed as a binary.

**Comment by lucascaton** [comment]
@coderhs I've added you as a collaborator!

**Comment by lucascaton** [comment]
Feel free to add your name to `README` and/or `gemspec` :)
