### ISSUE TITLE
Error invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by harguus** [lucascaton/code2pdf#9]
Na execusão do code2pdf em alguns arquivos é apresentado este erro:

Reading file SiNNP/modules/mod_menu/helper.php
/var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/regex_lexer.rb:304:in `skip': invalid byte sequence in UTF-8 (ArgumentError)
	from /var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/regex_lexer.rb:304:in `block in step'
	from /var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/regex_lexer.rb:289:in `each'
	from /var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/regex_lexer.rb:289:in `step'
	from /var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/regex_lexer.rb:270:in `stream_tokens'
	from /var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/lexer.rb:405:in `lex'
	from /var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/formatters/html_table.rb:27:in `each'
	from /var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/formatters/html_table.rb:27:in `stream'
	from /var/lib/gems/2.3.0/gems/rouge-3.1.0/lib/rouge/formatter.rb:37:in `format'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.1/lib/code2pdf/convert_to_pdf.rb:53:in `syntax_highlight'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.1/lib/code2pdf/convert_to_pdf.rb:37:in `block in pdf'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.1/lib/code2pdf/convert_to_pdf.rb:35:in `each'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.1/lib/code2pdf/convert_to_pdf.rb:35:in `pdf'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.1/lib/code2pdf/convert_to_pdf.rb:27:in `save'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.1/lib/code2pdf/convert_to_pdf.rb:20:in `initialize'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.1/bin/code2pdf:33:in `new'
	from /var/lib/gems/2.3.0/gems/code2pdf-0.4.1/bin/code2pdf:33:in `<top (required)>'
	from /usr/local/bin/code2pdf:23:in `load'
	from /usr/local/bin/code2pdf:23:in `<main>'

**Comment by lucascaton** [comment]
Hey @harguus, thanks for reporting this.

It looks like one or more of your files aren't properly formatted as UTF-8, can you please check?

**Comment by harguus** [comment]
Yes @lucascaton, it is what I suspect, but there are several that stayed like this and within your Joomla project, I re-created the files, copying the contents of each file and creating a new format in UTF-8 and even so the error continued.

**Comment by lucascaton** [comment]
Hey @harguus - is the project open-source? If so, can you please send me the link?
Otherwise, can you please upload one of the files somewhere so I can test/investigate it?

Cheers.

**Comment by harguus** [comment]
It is not open, I will send one of the files that gives this error.
Thank you very much for your help.

[helper.php.zip](https://github.com/lucascaton/code2pdf/files/1611640/helper.php.zip)

**Comment by lucascaton** [comment]
Hey @harguus - it works perfectly here 🤔
Check it out:

![screen capture on 2018-01-09 at 08-54-49](https://user-images.githubusercontent.com/86755/34696945-775562bc-f51c-11e7-9923-a350e3ce044f.gif)

**Comment by lucascaton** [comment]
@harguus, can you please make sure you're using at least version `0.4.1`?
I've just released `0.4.2` but both should work.

**Comment by lucascaton** [comment]
@harguus?
